spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.124.172.115:3306/booking?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: emoDB@1234
    hikari:
      connectionTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 50
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 10000
      poolName: booking-db-pool

  kafka:
    consumer:
      bootstrap-servers: 34.101.206.25:9092
    producer:
      bootstrap-servers: 34.101.206.25:9092