spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-hack2hire.onemount.dev:3306/user079-dijz?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: user079-dijz
    password: pwdtwxtac0knjddup
    hikari:
      connectionTimeout: 30000
      minimumIdle: 1
      maximumPoolSize: 50
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 10000
      poolName: booking-db-pool

  kafka:
    consumer:
      bootstrap-servers: 34.101.206.25:9092
    producer:
      bootstrap-servers: 34.101.206.25:9092